---
name: Continuous Integration

on:
  push:
    branches: [embedded]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  embedded_build:
    name: Embedded Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ["RelWithDebInfo"]
        gcc: [ "10.3-2021.10" ]
        target: ["tm4c123gh6pm", "tm4c1294ncpdt"]
        include:
          - gcc: "7-2018-q2"
            configuration: "RelWithDebInfo"
            target: "tm4c123gh6pm"
          - gcc: "8-2019-q3"
            configuration: "RelWithDebInfo"
            target: "tm4c123gh6pm"
          - gcc: "9-2020-q2"
            configuration: "RelWithDebInfo"
            target: "tm4c123gh6pm"
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install GNU Arm Embedded Toolchain ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@e9cd61b92edb079b14b2d0449b21f8a517121fe8 # v1.8.0
        with:
          release: ${{ matrix.gcc }}
      - uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
        with:
          key: ${{ matrix.gcc }}-${{ matrix.configuration }}-${{ matrix.target }}
      - run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends ninja-build xsltproc
          echo "::add-matcher::.github/matchers/gcc-problem-matcher.json"
          cmake --preset host -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build --preset host-${{ matrix.configuration }}
          cmake --preset ${{ matrix.target }} -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build --preset ${{ matrix.target }}-${{ matrix.configuration }}
