---
name: Continuous Integration

on:
  push:
    branches: [embedded]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  embedded_build:
    name: Embedded Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ["RelWithDebInfo"]
        gcc: [ "10.3-2021.10" ]
        target: ["tm4c123gh6pm", "tm4c1294ncpdt"]
        include:
          - gcc: "7-2018-q2"
            configuration: "RelWithDebInfo"
            target: "tm4c123gh6pm"
          - gcc: "8-2019-q3"
            configuration: "RelWithDebInfo"
            target: "tm4c123gh6pm"
          - gcc: "9-2020-q2"
            configuration: "RelWithDebInfo"
            target: "tm4c123gh6pm"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install GNU Arm Embedded Toolchain ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@87cd4a1b01dad71985108eff5e2f3577a815f6b4 # v1.6.2
        with:
          release: ${{ matrix.gcc }}
      - uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
        with:
          key: ${{ matrix.gcc }}-${{ matrix.configuration }}-${{ matrix.target }}
      - run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends ninja-build xsltproc
          echo "::add-matcher::.github/matchers/gcc-problem-matcher.json"
          cmake --preset host -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build --preset host-${{ matrix.configuration }}
          cmake --preset ${{ matrix.target }} -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build --preset ${{ matrix.target }}-${{ matrix.configuration }}
